#!gmake
#.SECONDARY:

include make.defs

# svg image sources
SVG_SOURCES =  \
	cat.svg \
    shine.svg \
    radial_spoked_shine.svg \
    mode_switch_slider_knob.svg \
    mode_switch_slider.svg \
    notelock_slider_knob.svg \
    notelock_slider.svg \
    51-power-glow.svg \
    51-power.svg \
    120-headphones-glow.svg \
    120-headphones.svg \
    cents_dial_tint.svg \
    scale_tape_tint.svg \
	panel_cutouts.svg \
    panel_cutouts_568h.svg \
	panel_texture.svg \
	panel_with_cutouts.svg \
    panel_with_cutouts_568h.svg \
    panel_for_view.svg \
    panel_for_view_568h.svg \
    panel_with_buttons.svg \
    panel_with_buttons_568h.svg \
    icon_texture.svg \
    icon_cutouts.svg \
    icon_with_cutouts.svg \
    icon_cutout_tint.svg \
    appstore_icon.svg \
    app_icon.svg \
    app_icon_ipad.svg \
    spotlight_icon.svg \
    spotlight_icon_ipad.svg \
    Default.svg \
    Default-568h.svg \
    iPhone-4S-0.svg \
    iPhone-5.svg \
    itunes_screen_shot_1_rgba.svg \
    itunes_screen_shot_1.svg \
    itunes_screen_shot_2.svg \
    itunes_screen_shot_1_rgba_568h.svg \
    itunes_screen_shot_1_568h.svg \
    itunes_screen_shot_2_568h.svg
    
            
# python sources that output svg to stdout    
PY_SOURCES = \
    cents_dial.py \
    scale_tape_english.py \
    scale_tape_northerneuropean.py \
    scale_tape_solfege_fixeddo.py \
    scale_tape_english_sharp.py \
    scale_tape_english_flat.py \
    radial_brushed_metal.py \
    icon_cents_dial.py \
    icon_scale_tape.py

#
# Note all .svg/.py sources need an matching .im file for image post-processing.
# This script/process should take a png via stdin and return a png via stdout 
#

#
# todo: auto-dependecies
#

include make.rules
